apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
  - image: rode
deploy:
  helm:
    releases:
      - name: rode
        chartPath: helm-chart
        skipBuildDependencies: true
        wait: true
        values:
          image: rode
        imageStrategy:
          helm: {}
portForward:
- resourceType: service
  resourceName: rode
  port: 443 
  localPort: 4000
profiles:
- name: local
  activation:
    - kubeContext: docker-for-desktop
  patches:
    - op: add
      path: /deploy/helm/releases/0/overrides
      value:
        grafeas:
          storageType: "memstore"
        localstack:
          enabled: true
          persistence:
            enabled: false
        extraEnv:
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          value: fake
        - name: AWS_SECRET_ACCESS_KEY
          value: fake
        - name: AWS_SQS_ENDPOINT
          value: rode-localstack:4576
        - name: AWS_EVENTS_ENDPOINT
          value: rode-localstack:4587
        - name: OPA_TRACE
          value: "0"

- name: production
  patches:
    - op: add
      path: /deploy/helm/flags
      value: 
        global:
          - '--tiller-namespace'
          - 'rode'
    - op: add
      path: /deploy/helm/releases/0/namespace
      value: rode
    - op: add
      path: /deploy/helm/releases/0/overrides
      value:
        image:
          pullPolicy: Always
        rbac:
          serviceAccountAnnotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::489130170427:role/RodeServiceAccount
